INSERT INTO comida (nombre, costo) VALUES ('Chorrillana', 12000);
INSERT INTO comida (nombre, costo) VALUES ('Completo', 2000);
INSERT INTO comida (nombre, costo) VALUES ('Hamburgesa' , 5000);
INSERT INTO comida (nombre, costo) VALUES ('Cazuela' , 3000);
INSERT INTO comida (nombre, costo) VALUES ('Pizza' , 8000);
INSERT INTO comida (nombre, costo) VALUES ('Fideos con carne' , 4000);
INSERT INTO comida (nombre, costo) VALUES ('Puré con Longaniza' , 4500);
INSERT INTO comida (nombre, costo) VALUES ('Bistec a lo pobre' , 6000);
INSERT INTO autos_entity (nombre, marca, modelo) VALUES ('auto1' , 'nissan', 'versa');
INSERT INTO autos_entity (nombre, marca, modelo) VALUES ('auto2' , 'toyota', 'corolla');
INSERT INTO autos_entity (nombre, marca, modelo) VALUES ('auto3' , 'mahindra', 'xuv500');
INSERT INTO autos_entity (nombre, marca, modelo) VALUES ('auto4' , 'tiggo', 'tiggo2');
INSERT INTO autos_entity (nombre, marca, modelo) VALUES ('auto5' , 'mazda', 'mazda3 sport');
INSERT INTO muebles_entity (nombre, tipo, valor) VALUES ('silla' , 'luis15', 15000);
INSERT INTO muebles_entity (nombre, tipo, valor) VALUES ('mesa' , 'luis15', 16000);
INSERT INTO muebles_entity (nombre, tipo, valor) VALUES ('sillon' , 'luis15', 17000);
INSERT INTO muebles_entity (nombre, tipo, valor) VALUES ('velador' , 'luis15', 18000);
INSERT INTO muebles_entity (nombre, tipo, valor) VALUES ('cama' , 'luis15', 19000);
INSERT INTO ropa_entity (nombre, marca, material) VALUES ('polera' , 'boulevar', 'algodon');
INSERT INTO ropa_entity (nombre, marca, material) VALUES ('pantalon' , 'louisVuitton', 'algodon');
INSERT INTO ropa_entity (nombre, marca, material) VALUES ('short' , 'channel', 'algodon');
INSERT INTO ropa_entity (nombre, marca, material) VALUES ('zapatillas' , 'lippi', 'cuero');