spring:
  thymeleaf.cache : false
  thymeleaf.reactive.max-chunk-size : 8192
  datasource:
    url : jdbc:h2:file:./data/mydb;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
    hikari:
     connection-timeout: 20000
     minimum-idle: 10
     maximum-pool-size: 10
     auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    #defer-datasource-initialization : true 
  h2:
   console:
     enabled: true
     path: /h2-console
     settings.trace: false
     settings.web-allow-others: false
  sql:
    init:
      mode: always
      continue-on-error: true
